; 🌈⚡ Bifrost - PHP Configuration (Development)

[PHP]
; Display errors in development
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Disable opcache validation for hot reload
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; XDebug Configuration
[XDebug]
xdebug.mode = ${XDEBUG_MODE}
xdebug.client_host = host.docker.internal
xdebug.start_with_request = trigger
xdebug.discover_client_host = false
